# Generated by Django 6.0.2 on 2026-03-12 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('minsalary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maxsalary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('responsibilities', models.JSONField(default=list)),
                ('requirements', models.JSONField(default=list)),
                ('type', models.CharField(max_length=50)),
                ('experience_level', models.CharField(max_length=50)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
