# Generated by Django 6.0.2 on 2026-03-12 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('company_industry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_industry.industry'),
        ),
    ]
